# Site settings
title: Caleb Churata
description: Caleb Churata's personal website - Mechatronics Engineer student at UTEC, interested in robotics and automation, sharing my code on Github, and more.
baseurl: #"/blog" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. https://example.com/
updated: 2024

# Landing Page
username: caleisach
typing_text: Mechatronic Engineering Student
email: caleb.churata@utec.edu.pe
linkedin_username: caleb-isaias-churata-berna-138140224
github_username: angor-root
twitter_username: angor.root
codepen_username: caleisach
dev_username: 
instagram_username: angor.root

# About Me Section
show_aboutme_card: true
about_me_title: Who Am I

# Skills Section
show_skills_card: true
skills_title: Skills

# Timeline Section
show_timeline_card: true
timeline_title: My Journey
cv_download_link: # https://github.com/longpdo/Awesome-CV/blob/master/examples/cv.pdf

# Projects Section
show_projects_card: true
show_projects: true
projects_title: Things I Have Built
show_os_projects: true
os_projects_title: Things I Contributed To Open Source

# CONTACT SECTION
show_contact_card: true
contact_title: Get In Touch

# Github-Metadata
repository: angor-root/angor-root.github.io
projects:
  # pushed or stars
  sort_by: stars
  exclude:
    archived: true
    forks: true
    projects:
    # - repo-name

# Google-analytics
google-analytics:
  id: "G-4C49TYLWZF"

plugins:
  - "jekyll-github-metadata"

exclude:
  [
    "_assets",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "node_modules",
    "package.json",
  ]
